package com.android.sample.ui.auth

// AI assistance: OpenAI Codex.
import android.content.Context
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.Credential
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import com.android.sample.model.authentication.AuthException
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption

/** UI boundary for the system account picker; Firebase authentication stays in AuthRepository. */
interface GoogleCredentialClient {
  suspend fun request(context: Context): Credential?

  suspend fun clearSession()
}

class GoogleSignInNotConfiguredException : IllegalStateException()

class AndroidGoogleCredentialClient(
    private val context: Context,
    private val manager: CredentialManager = CredentialManager.create(context),
) : GoogleCredentialClient {
  override suspend fun request(context: Context): Credential? {
    // Generated by the Google Services plugin from the web OAuth client in google-services.json.
    val resourceId =
        this.context.resources.getIdentifier(
            "default_web_client_id",
            "string",
            this.context.packageName,
        )
    if (resourceId == 0) throw GoogleSignInNotConfiguredException()
    val clientId = this.context.getString(resourceId)
    if (clientId.isBlank()) throw GoogleSignInNotConfiguredException()
    val request =
        GetCredentialRequest.Builder()
            .addCredentialOption(GetSignInWithGoogleOption.Builder(clientId).build())
            .build()
    return try {
      manager.getCredential(context = context, request = request).credential
    } catch (_: GetCredentialCancellationException) {
      null // Closing the picker is not an authentication failure.
    } catch (error: GetCredentialException) {
      throw AuthException.InvalidGoogleCredential(error)
    }
  }

  override suspend fun clearSession() {
    manager.clearCredentialState(ClearCredentialStateRequest())
  }
}
